export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACE_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!;
export const IMAGES_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;

export const PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_ID!;
export const MEMBER_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_ID!;
export const TASK_ID = process.env.NEXT_PUBLIC_APPWRITE_TASKS_ID!;
